export const LOADING = {
  SUBMIT: "SUBMIT_REGISTER",
};

export const CONTAINER = {
  WAITING_FOR_CONFIRMATION: "WAITING_FOR_CONFIRMATION",
};

export const STATUS = {
  SUCCESS: "SUCCESS_REGISTER",
  FAILED: "FAILED_REGISTER",
};
